# Generated by Django 2.2.7 on 2019-12-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('Todo', models.TextField()),
            ],
        ),
    ]
