# Generated by Django 2.2.7 on 2019-12-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_page', '0002_archivehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivehistory',
            name='Todo',
            field=models.CharField(max_length=100),
        ),
    ]
