# Generated by Django 2.2.7 on 2019-12-15 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_page', '0002_archivedtodoitem'),
        ('To_do_page', '0003_auto_20191215_1901'),
    ]

    operations = [
    ]
