# Generated by Django 2.2.7 on 2019-12-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_page', '0004_merge_20191215_2152'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArchivedToDoItem',
        ),
    ]
