# Generated by Django 2.2.7 on 2019-12-16 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_page', '0005_delete_archivedtodoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='Timecreated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='%Y-%m-%d %H:%M'),
            preserve_default=False,
        ),
    ]
