# Generated by Django 2.2.7 on 2019-12-20 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('To_do_page', '0007_auto_20191216_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivehistory',
            name='Timecreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archivehistory',
            name='action',
            field=models.CharField(default='Deleted', max_length=10),
            preserve_default=False,
        ),
    ]
